<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-01 22:00
=======
# Generated by Django 5.2.4 on 2025-08-02 17:38
>>>>>>> development

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
=======
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='movies/images/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('url', models.URLField(blank=True)),
>>>>>>> development
            ],
        ),
    ]
